name: SwiftLint

# Run on every pull request.
on: pull_request

jobs:
  swiftlint:
    name: "Lint Package"
    runs-on: macos-11.0 # Big Sur

    steps:
      - name: Checkout code base.
        uses: actions/checkout@v2

      - name: Install SwiftLint
        run: | 
          echo "$(PWD)"
          brew install swiftlint

      - name: SwiftLint Source
        run: | 
          sh ./bin/lint
